### ISSUE TITLE
Sourcing real-time data for TOAD

### ISSUE THREAD

**Issue by smooto** [hackoregon/transportation-congestion-analysis#11]
# Summary

TriMet's existing data infrastructure doesn't support the easy extraction of real-time information. The easiest option may be to scrape [GTFS](https://gtfs.org/) for this data, but if we choose this option, we may be missing out on important information from the congestion feed dataset. If we think a direct congestion-feed-to-cloud pipeline is the most attractive option for real-time updates to TOAD, then we may need buy-in from the agency to change that infrastructure. 

# Details

* Our connection at TriMet encourages us to scrape GTFS for real-time data. They report that extraction from the congestion feed is impractical on a day-to-day basis, and that the process can take months to complete.
* We already have code to scrape real-time date from GTFS directly into a PostgreSQL DB (though it's prototype-level & needs operationalizing); in general, code for real-time analytics from GTFS is readily available in both Python and R.
* Even if we already have real-time data from GTFS, there may be important, distinct advantages to creating a pipeline from the TriMet congestion feed. Ex.:
  * TriMet data has some passenger volume data; GTFS doesn't (from what we can tell).
    * _How would we do equity analyses without passenger counts (where do people get on on off the buses and trains, what time of day, etc.)?_
  * TriMet data is higher frequency, every ~5 sec., vs. every 30 seconds for GTFS real-time.
  * TriMet data has trip structure in the tables; for GTFS we'd have to infer that.
  * TriMet data has "stop_type" and disturbance stop information, a topic of primary interest for current/proposed analyses
* Such a pipeline may or may not be inhibitively difficult or costly to create; we'll need to understand the scope/scale of the present limitations before we can come up with a confident estimate for the necessary efforts.
* Depending on Metro/TriMet's buy-in to TOAD, we may also need to demonstrate (or at least argue for) the value of the proposed pipeline, and the changes needed to support it.
  * If our customer is the agency itself, then what are their pain points/motivations?
    * Equity (see above point re: passenger volume data)
    * Timeliness/reliability

# Questions

1. Within the context of our deliverable, what are the specific advantages to creating a direct congestion feed-to-cloud pipeline for collecting real-time data, rather relying on GTFS alone?
2. In concrete terms, what are the actual barriers to a congestion feed-to-cloud pipeline, and how difficult/costly would they be to overcome?
3. Are the advantages significant enough to warrant the difficulties/costs of overcoming these barriers?
4. If the answer to question 3 is "Yes," then how do we secure buy-in from TriMet (/the officials that call the shots for TriMet) to make the necessary infrastructural changes?

**Comment by znmeb** [comment]
GTFS real-time collector code for reference - https://github.com/znmeb/gtfs-collector

**Comment by znmeb** [comment]
- TriMet GTFS reference: https://developer.trimet.org/GTFS.shtml
- TriMet Vehicle Location service: https://developer.trimet.org/ws_docs/vehicle_locations_ws.shtml
- Google GTFS Realtime Reference: https://developers.google.com/transit/gtfs-realtime/reference/

**Comment by znmeb** [comment]
Is this still on the task list? Can I close it if not?
