### ISSUE TITLE
Move the reference tables to public schema

### ISSUE THREAD

**Issue by znmeb** [hackoregon/transportation-congestion-analysis#45]

**Comment by geophpherie** [comment]
A little context. It seems by default django will only look for the `public` schema. One way to get it to find other schemas is to pass the `OPTIONS` into settings. I haven't yet been able to test if the querying works for these tables though to confirm. Obviously having everything under one is the simplest approach.

```python
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "NAME": os.environ.get("POSTGRES_NAME"),
        "USER": os.environ.get("POSTGRES_USER"),
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": os.environ.get("POSTGRES_PORT"),
        "OPTIONS": {"options": "-c search_path=trimet_gis,public"},
    }
```

**Comment by znmeb** [comment]
closing for now - might reopen later
